### ISSUE TITLE
Babel Polyfill Error on 1.3.0

### ISSUE THREAD

**Issue by cpres** [auth0/auth0-analytics.js#14]
Whenever I try to run the 1.3.0 I receive the following error:
`Uncaught Error: only one instance of babel-polyfill is allowed`

I'm using babel for ES6 and I don't plan on reconfiguring my entire site to make auth0 analytics work. Luckily when I use 1.2.1 the issue doesn't persist so I'll be using that until it doesn't block regular site babel usage.

**Comment by francocorreasosa** [comment]
Hey @cpres! Sorry for the delay. I'll investigate what's happening and keep you updated.

**Comment by francocorreasosa** [comment]
The issue has been solved in https://github.com/auth0/auth0-analytics.js/commit/2bdcbeacc013616d5d7ecc00a9704b3baabd53a2. Thank you for reporting this!

**Comment by johnnabil** [comment]
I used 1.3.1 and still have the same issue!

**Comment by francocorreasosa** [comment]
Hi @johnnabil. What version of `babel-polyfill` are you using?

**Comment by NShulzhenko** [comment]
@francocorreasosa I have an old vue-project with manually configured webpack v3 and I import babel-poylfill in main.js file where Vue app is created. Still got issue `Uncaught Error: only one instance of babel-polyfill is allowed`. Version 1.3.1 of analytics is used from https://cdn.auth0.com/js/analytics/1.3.1/analytics.min.js.

 babel-polyfill in packaje json is ^6.26.0. Could You help with it?
