### ISSUE TITLE
from a hosted lock, analytics 1.3.1 is returning a 403, while analytics 1.3.0 is loading fine

### ISSUE THREAD

**Issue by rDr4g0n** [auth0/auth0-analytics.js#16]
I am using a hosted lock and trying to load analytics in it. The docs say to construct the cdn link by getting the version number of the latest release from github (and includes a link to the github releases page).  

The latest is 1.3.1, but the request for `https://cdn.auth0.com/js/analytics/1.3.1/analytics.min.js` fails with a 403.  

Requesting 1.3.0 with `https://cdn.auth0.com/js/analytics/1.3.0/analytics.min.js` succeeds.

**Comment by mattwhetton** [comment]
This is still happening

**Comment by machuga** [comment]
We're looking into it. Thanks, and apologies for the inconvenience!

**Comment by machuga** [comment]
@rDr4g0n and @mattwhetton Can you please try now? The CDN has been updated.

**Comment by rDr4g0n** [comment]
@machuga works! thanks
