### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by fyockm** [auth0/auth0-analytics.js#7]
Current dependency on `auth0-tag-manager` (which uses `Promise`) leads to a `Promise not defined` error in IE11 (unless you manually provide a polyfill)

Need to update docs or provide polyfill

https://auth0.slack.com/archives/C44EZEWCT/p1502270629725385

**Comment by purch-FE** [comment]
IE 11 is still a decent portion of users that ultimately would need to access sites through their credentials:  IE 11 usage is currently at 3.36% source : https://www.w3counter.com/globalstats.php
Please let us know the ETA for this resolution, we think the auth0 library should not assume the client can support this and should have a fallback baked in.

**Comment by ntotten** [comment]
Fixed in release 1.3.0
